"""add unique constraint to sleep_surveys

Revision ID: 03872dc995c6
Revises: 3389ee1e78a3
Create Date: 2025-07-28 14:07:34.907986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03872dc995c6'
down_revision: Union[str, Sequence[str], None] = '3389ee1e78a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_surveys', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sleep_survey_user_date', ['user_id', 'survey_date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_surveys', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sleep_survey_user_date', type_='unique')

    # ### end Alembic commands ###
