"""Add password_hash and salt fields to users table

Revision ID: 248e783e1c1b
Revises: 5d9c6a8bd44e
Create Date: 2025-06-21 15:01:40.197461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248e783e1c1b'
down_revision: Union[str, Sequence[str], None] = '5d9c6a8bd44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('salt', sa.String(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
