"""add my sleep survey table

Revision ID: 2e77dff556ce
Revises: a51d5dcb213a
Create Date: 2025-07-27 11:35:29.785170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e77dff556ce'
down_revision: Union[str, Sequence[str], None] = 'a51d5dcb213a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_sleep_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('durmo_mal_ou_bem', sa.Integer(), nullable=False),
    sa.Column('gosto_de_dormir', sa.Integer(), nullable=False),
    sa.Column('acho_sono_importante_para_mim', sa.Integer(), nullable=False),
    sa.Column('o_que_sei_sobre_sono', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('my_sleep_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_my_sleep_surveys_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_sleep_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_my_sleep_surveys_id'))

    op.drop_table('my_sleep_surveys')
    # ### end Alembic commands ###
