"""remove relationship survey table

Revision ID: 3389ee1e78a3
Revises: ec951403bba1
Create Date: 2025-07-28 13:28:06.616757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3389ee1e78a3'
down_revision: Union[str, Sequence[str], None] = 'ec951403bba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_surveys_id'))

    op.drop_table('relationship_surveys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consciencia_importancia_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aceitacao_caracteristicas_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('habitos_sono_regulares', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conhecimento_tempo_sono_necessario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bem_estar_ritmo_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('horario_sono_por_necessidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conhecimento_padrao_sono_vigilia', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aceitacao_dormir_mal_normal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evitar_alteracoes_padrao_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conhecimento_fatores_prejudicam_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admissao_sono_involuntario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prioridade_sono_rotina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conhecimento_ecrans_dificultam_adormecer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nao_culpa_dormir_mal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reorganizacao_horarios_para_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacao_alimentos_bebidas_influenciam_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aceitacao_dormir_nem_sempre_bem', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ambiente_favoravel_qualidade_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conhecimento_luz_exercicio_influencia_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manter_calma_dificuldade_adormecer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correcao_comportamentos_nocivos_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consciencia_trabalho_serao_prejudica_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tolerancia_insonia_pessoal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evitar_stress_antes_dormir', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacao_estilo_vida_impacto_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admissao_variacao_sono_vida', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comportamentos_proativos_evitar_problemas_sono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('survey_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('relationship_surveys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('relationship_surveys_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('uq_relationship_survey_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('relationship_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_surveys_id'), ['id'], unique=False)

    # ### end Alembic commands ###
