"""add daily_sleep_survey table

Revision ID: 42fb2e2163d1
Revises: baeef18100b1
Create Date: 2025-06-22 10:44:09.611050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fb2e2163d1'
down_revision: Union[str, Sequence[str], None] = 'baeef18100b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sleep_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hora_levantaste_hoje', sa.Time(), nullable=False),
    sa.Column('hora_deitaste_ontem', sa.Time(), nullable=False),
    sa.Column('tempo_ate_adormecer', sa.Integer(), nullable=False),
    sa.Column('vezes_acordaste_noite', sa.Integer(), nullable=False),
    sa.Column('horas_que_dormiste', sa.Integer(), nullable=False),
    sa.Column('qualidade_sono_noite', sa.Integer(), nullable=False),
    sa.Column('observacao_noite_passada', sa.String(), nullable=True),
    sa.Column('survey_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'survey_date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_sleep_surveys_id'), 'daily_sleep_surveys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_sleep_surveys_id'), table_name='daily_sleep_surveys')
    op.drop_table('daily_sleep_surveys')
    # ### end Alembic commands ###
