"""add relationship survey table

Revision ID: 6522d754db51
Revises: 42fb2e2163d1
Create Date: 2025-06-22 14:42:49.284787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6522d754db51'
down_revision: Union[str, Sequence[str], None] = '42fb2e2163d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consciencia_importancia_sono', sa.Integer(), nullable=False),
    sa.Column('aceitacao_caracteristicas_sono', sa.Integer(), nullable=False),
    sa.Column('habitos_sono_regulares', sa.Integer(), nullable=False),
    sa.Column('conhecimento_tempo_sono_necessario', sa.Integer(), nullable=False),
    sa.Column('bem_estar_ritmo_sono', sa.Integer(), nullable=False),
    sa.Column('horario_sono_por_necessidade', sa.Integer(), nullable=False),
    sa.Column('conhecimento_padrao_sono_vigilia', sa.Integer(), nullable=False),
    sa.Column('aceitacao_dormir_mal_normal', sa.Integer(), nullable=False),
    sa.Column('evitar_alteracoes_padrao_sono', sa.Integer(), nullable=False),
    sa.Column('conhecimento_fatores_prejudicam_sono', sa.Integer(), nullable=False),
    sa.Column('admissao_sono_involuntario', sa.Integer(), nullable=False),
    sa.Column('prioridade_sono_rotina', sa.Integer(), nullable=False),
    sa.Column('conhecimento_ecrans_dificultam_adormecer', sa.Integer(), nullable=False),
    sa.Column('nao_culpa_dormir_mal', sa.Integer(), nullable=False),
    sa.Column('reorganizacao_horarios_para_sono', sa.Integer(), nullable=False),
    sa.Column('identificacao_alimentos_bebidas_influenciam_sono', sa.Integer(), nullable=False),
    sa.Column('aceitacao_dormir_nem_sempre_bem', sa.Integer(), nullable=False),
    sa.Column('ambiente_favoravel_qualidade_sono', sa.Integer(), nullable=False),
    sa.Column('conhecimento_luz_exercicio_influencia_sono', sa.Integer(), nullable=False),
    sa.Column('manter_calma_dificuldade_adormecer', sa.Integer(), nullable=False),
    sa.Column('correcao_comportamentos_nocivos_sono', sa.Integer(), nullable=False),
    sa.Column('consciencia_trabalho_serao_prejudica_sono', sa.Integer(), nullable=False),
    sa.Column('tolerancia_insonia_pessoal', sa.Integer(), nullable=False),
    sa.Column('evitar_stress_antes_dormir', sa.Integer(), nullable=False),
    sa.Column('identificacao_estilo_vida_impacto_sono', sa.Integer(), nullable=False),
    sa.Column('admissao_variacao_sono_vida', sa.Integer(), nullable=False),
    sa.Column('comportamentos_proativos_evitar_problemas_sono', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_relationship_survey_user')
    )
    with op.batch_alter_table('relationship_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_surveys_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_surveys_id'))

    op.drop_table('relationship_surveys')
    # ### end Alembic commands ###
