"""add sleep survey table

Revision ID: 7a519a2b9e66
Revises: 2b8aedaadad3
Create Date: 2025-06-21 17:17:45.440444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a519a2b9e66'
down_revision: Union[str, Sequence[str], None] = '2b8aedaadad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dormir_pouco_agressivo_irritadico', sa.Boolean(), nullable=False),
    sa.Column('adormecer_aumenta_temperatura_corpo', sa.Boolean(), nullable=False),
    sa.Column('hora_dormir_nao_influencia_qualidade_sono', sa.Boolean(), nullable=False),
    sa.Column('computador_noite_prejudica_sono', sa.Boolean(), nullable=False),
    sa.Column('adolescentes_devem_dormir_8_horas', sa.Boolean(), nullable=False),
    sa.Column('concentracao_independente_do_sono', sa.Boolean(), nullable=False),
    sa.Column('dormir_sem_atividade_cerebral', sa.Boolean(), nullable=False),
    sa.Column('indiferente_dormir_dia_ou_noite', sa.Boolean(), nullable=False),
    sa.Column('comer_muito_antes_prejudica_sono', sa.Boolean(), nullable=False),
    sa.Column('mensagens_noite_prejudica_sono', sa.Boolean(), nullable=False),
    sa.Column('dormir_pouco_aumenta_doencas', sa.Boolean(), nullable=False),
    sa.Column('estudar_tarde_igual_eficaz_dia', sa.Boolean(), nullable=False),
    sa.Column('muita_luz_noite_altera_ritmo', sa.Boolean(), nullable=False),
    sa.Column('esforco_fisico_ajuda_adormecer', sa.Boolean(), nullable=False),
    sa.Column('compensar_sono_perdido_noite_seguinte', sa.Boolean(), nullable=False),
    sa.Column('sono_insuficiente_engordar', sa.Boolean(), nullable=False),
    sa.Column('sesta_nao_afeta_sono_noite', sa.Boolean(), nullable=False),
    sa.Column('luz_sol_ajuda_dormir_bem', sa.Boolean(), nullable=False),
    sa.Column('dormir_pouco_aumenta_acidentes', sa.Boolean(), nullable=False),
    sa.Column('varios_tipos_sono_noite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_surveys_id'), 'sleep_surveys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_surveys_id'), table_name='sleep_surveys')
    op.drop_table('sleep_surveys')
    # ### end Alembic commands ###
