"""add cleveland survey table

Revision ID: a51d5dcb213a
Revises: 6522d754db51
Create Date: 2025-07-27 11:22:31.385996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51d5dcb213a'
down_revision: Union[str, Sequence[str], None] = '6522d754db51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleveland_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adormeco_durante_aulas_manha', sa.Integer(), nullable=False),
    sa.Column('consigo_aguentar_dia_inteiro_escola_sem_cansaco', sa.Integer(), nullable=False),
    sa.Column('adormeco_ultima_aula_dia', sa.Integer(), nullable=False),
    sa.Column('fico_sonolento_carro_mais_5_minutos', sa.Integer(), nullable=False),
    sa.Column('fico_bem_acordado_durante_todo_dia', sa.Integer(), nullable=False),
    sa.Column('adormeco_escola_aulas_tarde', sa.Integer(), nullable=False),
    sa.Column('sinto_me_desperto_durante_aulas', sa.Integer(), nullable=False),
    sa.Column('sinto_me_sonolento_fim_dia_depois_aulas', sa.Integer(), nullable=False),
    sa.Column('sinto_me_sonolento_autocarro_atividade_escola', sa.Integer(), nullable=False),
    sa.Column('de_manha_quando_estou_escola_adormeco', sa.Integer(), nullable=False),
    sa.Column('quando_estou_aulas_sinto_me_bem_desperto', sa.Integer(), nullable=False),
    sa.Column('sinto_me_sonolento_trabalhos_casa_noite_escola', sa.Integer(), nullable=False),
    sa.Column('estou_bem_desperto_ultima_aula_dia', sa.Integer(), nullable=False),
    sa.Column('adormeco_quando_ando_carro_autocarro_comboio', sa.Integer(), nullable=False),
    sa.Column('durante_dia_escola_momentos_acabei_adormecer', sa.Integer(), nullable=False),
    sa.Column('adormeco_quando_faco_trabalhos_escola_noite_casa', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleveland_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleveland_surveys_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleveland_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleveland_surveys_id'))

    op.drop_table('cleveland_surveys')
    # ### end Alembic commands ###
