"""add survey_date to sleep_survey table

Revision ID: baeef18100b1
Revises: c22cef4a7a6b
Create Date: 2025-06-21 23:16:26.497943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeef18100b1'
down_revision: Union[str, Sequence[str], None] = 'c22cef4a7a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to handle the column addition with default value
    with op.batch_alter_table('sleep_surveys', schema=None) as batch_op:
        # Add column as nullable first, then populate and make non-nullable
        batch_op.add_column(sa.Column('survey_date', sa.Date(), nullable=True))
    
    # Populate the new column with current date for existing records
    op.execute("UPDATE sleep_surveys SET survey_date = DATE('now') WHERE survey_date IS NULL")
    
    # Now make the column non-nullable with batch mode
    with op.batch_alter_table('sleep_surveys', schema=None) as batch_op:
        batch_op.alter_column('survey_date', nullable=False, server_default=sa.text('(CURRENT_DATE)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite
    with op.batch_alter_table('sleep_surveys', schema=None) as batch_op:
        batch_op.drop_column('survey_date')
    # ### end Alembic commands ###
