"""add gender school and school_year to user table

Revision ID: c22cef4a7a6b
Revises: 7a519a2b9e66
Create Date: 2025-06-21 23:02:51.649889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as psql


# revision identifiers, used by Alembic.
revision: str = 'c22cef4a7a6b'
down_revision: Union[str, Sequence[str], None] = '7a519a2b9e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    if op.get_bind().engine.name == "postgresql":
        gender_enum = psql.ENUM("M", "F", "O", name="gender")
        gender_enum.create(op.get_bind(), checkfirst=True)
    else:
        gender_enum = sa.Enum('M', 'F', 'O', name='gender')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', gender_enum, nullable=False, server_default='O'))
    op.add_column('users', sa.Column('school', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('school_year', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'school_year')
    op.drop_column('users', 'school')
    op.drop_column('users', 'gender')

    gender_enum = psql.ENUM("M", "F", "O", name="gender")
    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
